In [ ]:
# Matches stronger H₂S events with RTMA weather variables
# and creates wind-speed and wind-direction summaries.

from pathlib import Path
import pandas as pd
import numpy as np

# Mount Google Drive in Colab
from google.colab import drive
drive.mount("/content/drive")

# Main project folders
DATA_RAW = Path("/content/drive/MyDrive/STAT596/Project596_datafiles")
DATA_PROCESSED = DATA_RAW / "processed_data"
FIGURES = DATA_RAW / "figures"
TABLES = DATA_RAW / "tables"
NOTEBOOKS = DATA_RAW / "notebooks"

# Input files
current_h2s_path = DATA_PROCESSED / "h2s_events_clean_2024_2025.csv"
rtma_matched_input_path = DATA_RAW / "h2s_rtma_full_matched_60_events.csv"

# Planned output file
rtma_matched_output_path = DATA_PROCESSED / "h2s_rtma_matched_events_clean.csv"

# Check files
print("H2S + RTMA audit setup")
print("=" * 60)

print("Current cleaned H2S file:")
print(current_h2s_path)
print("File exists:", current_h2s_path.exists())

print("\nRTMA matched input file:")
print(rtma_matched_input_path)
print("File exists:", rtma_matched_input_path.exists())

print("\nPlanned cleaned RTMA output:")
print(rtma_matched_output_path)

# Load files only if both exist
if current_h2s_path.exists() and rtma_matched_input_path.exists():
    h2s_current = pd.read_csv(current_h2s_path)
    h2s_rtma_raw = pd.read_csv(rtma_matched_input_path)

    print("\nCurrent cleaned H2S shape:", h2s_current.shape)
    print("RTMA matched raw shape:", h2s_rtma_raw.shape)

    print("\nCurrent H2S columns:")
    for col in h2s_current.columns:
        print("-", col)

    print("\nRTMA matched columns:")
    for col in h2s_rtma_raw.columns:
        print("-", col)

    print("\nCurrent H2S preview:")
    display(h2s_current.head())

    print("\nRTMA matched preview:")
    display(h2s_rtma_raw.head())
else:
    print("\nOne or both files are missing. Check the file names or folder location before moving forward.")

Mounted at /content/drive
H2S + RTMA audit setup
============================================================
Current cleaned H2S file:
/content/drive/MyDrive/STAT596/Project596_datafiles/processed_data/h2s_events_clean_2024_2025.csv
File exists: True

RTMA matched input file:
/content/drive/MyDrive/STAT596/Project596_datafiles/h2s_rtma_full_matched_60_events.csv
File exists: True

Planned cleaned RTMA output:
/content/drive/MyDrive/STAT596/Project596_datafiles/processed_data/h2s_rtma_matched_events_clean.csv

Current cleaned H2S shape: (597, 25)
RTMA matched raw shape: (60, 52)

Current H2S columns:
- datetime_local
- date
- year
- month
- hour
- station_name_clean
- location_clean
- h2s_ppb
- h2s_level_clean
- elevated_h2s_event
- orange_h2s_event
- valid_h2s_record
- h2s_ppb_original
- h2s_ppb_clean
- h2s_level
- exceedance_30ppb
- exceedance_200ppb
- nighttime_flag
- analysis_period
- review_status
- negative_value_flag
- missing_h2s_flag
- source
- source_note
- notes

RTMA matched columns:
- datetime_utc
- target_lat
- target_lon
- temperature_2m
- temperature_2m_units
- temperature_2m_grid_lat
- temperature_2m_grid_lon
- dewpoint_2m
- dewpoint_2m_units
- dewpoint_2m_grid_lat
- dewpoint_2m_grid_lon
- wind_u_10m
- wind_u_10m_units
- wind_u_10m_grid_lat
- wind_u_10m_grid_lon
- wind_v_10m
- wind_v_10m_units
- wind_v_10m_grid_lat
- wind_v_10m_grid_lon
- wind_direction_10m
- wind_direction_10m_units
- wind_direction_10m_grid_lat
- wind_direction_10m_grid_lon
- wind_speed_10m
- wind_speed_10m_units
- wind_speed_10m_grid_lat
- wind_speed_10m_grid_lon
- wind_gust_10m
- wind_gust_10m_units
- wind_gust_10m_grid_lat
- wind_gust_10m_grid_lon
- visibility_surface
- visibility_surface_units
- visibility_surface_grid_lat
- visibility_surface_grid_lon
- wind_speed_10m_mph
- wind_gust_10m_mph
- visibility_surface_km
- visibility_surface_miles
- temperature_2m_f
- dewpoint_2m_f
- date
- time
- datetime_local
- datetime_utc_original
- location_clean
- h2s_ppb
- h2s_level
- exceedance_30ppb
- exceedance_200ppb
- nighttime_flag
- analysis_period

Current H2S preview:

,datetime_local,date,year,month,hour,station_name_clean,location_clean,h2s_ppb,h2s_level_clean,elevated_h2s_event,...,exceedance_30ppb,exceedance_200ppb,nighttime_flag,analysis_period,review_status,negative_value_flag,missing_h2s_flag,source,source_note,notes
0,2024-09-12 11:00:00,2024-09-12,2024,2024-09,11,San Ysidro - Fire Station #29,SAN YSIDRO,NaN,Missing/Not visible,False,...,0,0,0,Immediate post-emergency,missing_visible,0,1,SDAPCD Power BI dashboard screen recording,Manually extracted from SDAPCD public Power BI...,from initial screen-recording extraction
1,2024-09-25 14:00:00,2024-09-25,2024,2024-09,14,San Ysidro - Fire Station #29,SAN YSIDRO,0.1,Green (0-4.9 ppB),False,...,0,0,0,Immediate post-emergency,numeric,0,0,SDAPCD Power BI dashboard screen recording,Manually extracted from SDAPCD public Power BI...,from initial screen-recording extraction
2,2024-09-25 15:00:00,2024-09-25,2024,2024-09,15,San Ysidro - Fire Station #29,SAN YSIDRO,0.1,Green (0-4.9 ppB),False,...,0,0,0,Immediate post-emergency,numeric,0,0,SDAPCD Power BI dashboard screen recording,Manually extracted from SDAPCD public Power BI...,from initial screen-recording extraction
3,2024-09-25 16:00:00,2024-09-25,2024,2024-09,16,San Ysidro - Fire Station #29,SAN YSIDRO,0.1,Green (0-4.9 ppB),False,...,0,0,0,Immediate post-emergency,numeric,0,0,SDAPCD Power BI dashboard screen recording,Manually extracted from SDAPCD public Power BI...,from initial screen-recording extraction
4,2024-09-25 17:00:00,2024-09-25,2024,2024-09,17,San Ysidro - Fire Station #29,SAN YSIDRO,0.1,Green (0-4.9 ppB),False,...,0,0,0,Immediate post-emergency,numeric,0,0,SDAPCD Power BI dashboard screen recording,Manually extracted from SDAPCD public Power BI...,from initial screen-recording extraction

RTMA matched preview:

,datetime_utc,target_lat,target_lon,temperature_2m,temperature_2m_units,temperature_2m_grid_lat,temperature_2m_grid_lon,dewpoint_2m,dewpoint_2m_units,dewpoint_2m_grid_lat,...,time,datetime_local,datetime_utc_original,location_clean,h2s_ppb,h2s_level,exceedance_30ppb,exceedance_200ppb,nighttime_flag,analysis_period
0,2024-09-26 02:00,32.552,-117.0431,17.860010,C,32.550775,-117.038140,15.629999,C,32.550775,...,7:00:00 PM,2024-09-25 19:00:00,2024-09-26 02:00:00+00:00,SAN YSIDRO,10.0,Yellow (5-29.9 ppB),0,0,0,Immediate post-emergency
1,2024-12-07 08:00,32.579,-117.0910,11.830011,C,32.588111,-117.099856,5.999994,C,32.588111,...,12:00:00 AM,2024-12-07 00:00:00,2024-12-07 08:00:00+00:00,NESTOR - BES,17.8,Yellow (5-29.9 ppB),0,0,1,Immediate post-emergency
2,2024-12-07 08:00,32.552,-117.0431,11.339990,C,32.550775,-117.038140,5.580011,C,32.550775,...,12:00:00 AM,2024-12-07 00:00:00,2024-12-07 08:00:00+00:00,SAN YSIDRO,10.8,Yellow (5-29.9 ppB),0,0,1,Immediate post-emergency
3,2024-12-07 09:00,32.579,-117.0910,12.360010,C,32.588111,-117.099856,5.559991,C,32.588111,...,1:00:00 AM,2024-12-07 01:00:00,2024-12-07 09:00:00+00:00,NESTOR - BES,20.1,Yellow (5-29.9 ppB),0,0,1,Immediate post-emergency
4,2024-12-07 09:00,32.552,-117.0431,12.459985,C,32.550775,-117.038140,3.909998,C,32.550775,...,1:00:00 AM,2024-12-07 01:00:00,2024-12-07 09:00:00+00:00,SAN YSIDRO,15.0,Yellow (5-29.9 ppB),0,0,1,Immediate post-emergency

In [ ]:
h2s_current_check = h2s_current.copy()
h2s_rtma_check = h2s_rtma_raw.copy()

# Standardize datetime fields
h2s_current_check["datetime_local"] = pd.to_datetime(h2s_current_check["datetime_local"], errors="coerce")
h2s_rtma_check["datetime_local"] = pd.to_datetime(h2s_rtma_check["datetime_local"], errors="coerce")
h2s_rtma_check["datetime_utc"] = pd.to_datetime(h2s_rtma_check["datetime_utc"], errors="coerce")

# Standardize location and H2S values
h2s_current_check["location_clean"] = h2s_current_check["location_clean"].astype(str).str.strip().str.upper()
h2s_rtma_check["location_clean"] = h2s_rtma_check["location_clean"].astype(str).str.strip().str.upper()

h2s_current_check["h2s_ppb"] = pd.to_numeric(h2s_current_check["h2s_ppb"], errors="coerce")
h2s_rtma_check["h2s_ppb"] = pd.to_numeric(h2s_rtma_check["h2s_ppb"], errors="coerce")

# Create rounded H2S value for safer matching
h2s_current_check["h2s_ppb_round"] = h2s_current_check["h2s_ppb"].round(3)
h2s_rtma_check["h2s_ppb_round"] = h2s_rtma_check["h2s_ppb"].round(3)

# Recreate threshold flags for audit
h2s_current_check["valid_h2s_record"] = h2s_current_check["h2s_ppb"].notna()
h2s_current_check["elevated_ge_5"] = h2s_current_check["valid_h2s_record"] & (h2s_current_check["h2s_ppb"] >= 5)
h2s_current_check["elevated_ge_10"] = h2s_current_check["valid_h2s_record"] & (h2s_current_check["h2s_ppb"] >= 10)
h2s_current_check["orange_ge_30"] = h2s_current_check["valid_h2s_record"] & (h2s_current_check["h2s_ppb"] >= 30)

h2s_rtma_check["elevated_ge_5"] = h2s_rtma_check["h2s_ppb"].notna() & (h2s_rtma_check["h2s_ppb"] >= 5)
h2s_rtma_check["elevated_ge_10"] = h2s_rtma_check["h2s_ppb"].notna() & (h2s_rtma_check["h2s_ppb"] >= 10)
h2s_rtma_check["orange_ge_30"] = h2s_rtma_check["h2s_ppb"].notna() & (h2s_rtma_check["h2s_ppb"] >= 30)

print("H2S + RTMA match audit")
print("=" * 60)

print("Current cleaned H2S threshold counts:")
print("Total rows:", len(h2s_current_check))
print("Valid numeric H2S records:", h2s_current_check["valid_h2s_record"].sum())
print("Events >= 5 ppb:", h2s_current_check["elevated_ge_5"].sum())
print("Events >= 10 ppb:", h2s_current_check["elevated_ge_10"].sum())
print("Events >= 30 ppb:", h2s_current_check["orange_ge_30"].sum())

print("\nRTMA matched threshold counts:")
print("Total RTMA rows:", len(h2s_rtma_check))
print("Events >= 5 ppb:", h2s_rtma_check["elevated_ge_5"].sum())
print("Events >= 10 ppb:", h2s_rtma_check["elevated_ge_10"].sum())
print("Events >= 30 ppb:", h2s_rtma_check["orange_ge_30"].sum())

print("\nRTMA date/time coverage:")
print("Start datetime_local:", h2s_rtma_check["datetime_local"].min())
print("End datetime_local:", h2s_rtma_check["datetime_local"].max())
print("Unique dates:", h2s_rtma_check["datetime_local"].dt.date.nunique())
print("Unique stations:", h2s_rtma_check["location_clean"].nunique())

# Exact match check: datetime + station + H2S value
match_keys = ["datetime_local", "location_clean", "h2s_ppb_round"]

rtma_exact_match = h2s_rtma_check.merge(
    h2s_current_check[match_keys].drop_duplicates(),
    on=match_keys,
    how="left",
    indicator=True
)

exact_matches = (rtma_exact_match["_merge"] == "both").sum()
exact_nonmatches = (rtma_exact_match["_merge"] == "left_only").sum()

print("\nExact match check using datetime_local + location_clean + h2s_ppb:")
print("Exact matches:", exact_matches)
print("Exact non-matches:", exact_nonmatches)

# Looser match check: datetime + station only
loose_keys = ["datetime_local", "location_clean"]

rtma_loose_match = h2s_rtma_check.merge(
    h2s_current_check[loose_keys].drop_duplicates(),
    on=loose_keys,
    how="left",
    indicator=True
)

loose_matches = (rtma_loose_match["_merge"] == "both").sum()
loose_nonmatches = (rtma_loose_match["_merge"] == "left_only").sum()

print("\nLoose match check using datetime_local + location_clean only:")
print("Loose matches:", loose_matches)
print("Loose non-matches:", loose_nonmatches)

print("\nRTMA rows by station:")
display(h2s_rtma_check["location_clean"].value_counts().reset_index(name="rtma_rows"))

print("\nRTMA H2S value summary:")
display(h2s_rtma_check["h2s_ppb"].describe())

print("\nCurrent cleaned H2S events >= 10 ppb by station:")
display(
    h2s_current_check[h2s_current_check["elevated_ge_10"]]
    .groupby("location_clean")
    .agg(
        events_ge_10=("h2s_ppb", "size"),
        max_h2s_ppb=("h2s_ppb", "max")
    )
    .reset_index()
    .sort_values("events_ge_10", ascending=False)
)

print("\nRTMA exact non-matching rows, if any:")
display(
    rtma_exact_match[rtma_exact_match["_merge"] == "left_only"]
    [["datetime_local", "location_clean", "h2s_ppb", "h2s_level"]]
    .head(20)
)

H2S + RTMA match audit
============================================================
Current cleaned H2S threshold counts:
Total rows: 597
Valid numeric H2S records: 448
Events >= 5 ppb: 129
Events >= 10 ppb: 60
Events >= 30 ppb: 11

RTMA matched threshold counts:
Total RTMA rows: 60
Events >= 5 ppb: 60
Events >= 10 ppb: 60
Events >= 30 ppb: 11

RTMA date/time coverage:
Start datetime_local: 2024-09-25 19:00:00
End datetime_local: 2025-07-08 04:00:00
Unique dates: 11
Unique stations: 3

Exact match check using datetime_local + location_clean + h2s_ppb:
Exact matches: 60
Exact non-matches: 0

Loose match check using datetime_local + location_clean only:
Loose matches: 60
Loose non-matches: 0

RTMA rows by station:

  location_clean  rtma_rows
0   NESTOR - BES         31
1     SAN YSIDRO         20
2   IB CIVIC CTR          9

RTMA H2S value summary:

count     60.00000
mean      33.45500
std       53.36997
min       10.00000
25%       12.35000
50%       16.30000
75%       26.57500
max      295.60000
Name: h2s_ppb, dtype: float64

Current cleaned H2S events >= 10 ppb by station:

  location_clean  events_ge_10  max_h2s_ppb
1   NESTOR - BES            31        295.6
2     SAN YSIDRO            20         45.5
0   IB CIVIC CTR             9         27.9

RTMA exact non-matching rows, if any:

Empty DataFrame
Columns: [datetime_local, location_clean, h2s_ppb, h2s_level]
Index: []

Note to self:
The H2S + RTMA weather dataset is a weather-matched subset of the stronger elevated H2S events, defined as H2S >= 10 ppb. It is used to examine wind and weather conditions during higher-intensity H2S events, not all elevated H2S records.

In [ ]:
# Prepares the H2S + RTMA matched subset, where all events are H2S >= 10 ppb and have
# hourly weather/wind variables.

h2s_rtma_clean = h2s_rtma_raw.copy()

# Parse datetime fields
h2s_rtma_clean["datetime_local"] = pd.to_datetime(h2s_rtma_clean["datetime_local"], errors="coerce")
h2s_rtma_clean["datetime_utc"] = pd.to_datetime(h2s_rtma_clean["datetime_utc"], errors="coerce")
h2s_rtma_clean["date"] = pd.to_datetime(h2s_rtma_clean["date"], errors="coerce").dt.date

# Standardize location field
h2s_rtma_clean["location_clean"] = h2s_rtma_clean["location_clean"].astype(str).str.strip().str.upper()

# Convert key numeric columns
numeric_cols = [
    "target_lat",
    "target_lon",
    "h2s_ppb",
    "temperature_2m",
    "dewpoint_2m",
    "wind_u_10m",
    "wind_v_10m",
    "wind_direction_10m",
    "wind_speed_10m",
    "wind_gust_10m",
    "visibility_surface",
    "wind_speed_10m_mph",
    "wind_gust_10m_mph",
    "visibility_surface_km",
    "visibility_surface_miles",
    "temperature_2m_f",
    "dewpoint_2m_f"
]

for col in numeric_cols:
    if col in h2s_rtma_clean.columns:
        h2s_rtma_clean[col] = pd.to_numeric(h2s_rtma_clean[col], errors="coerce")

# Create clean event flags
h2s_rtma_clean["valid_h2s_record"] = h2s_rtma_clean["h2s_ppb"].notna()
h2s_rtma_clean["elevated_h2s_event"] = h2s_rtma_clean["valid_h2s_record"] & (h2s_rtma_clean["h2s_ppb"] >= 5)
h2s_rtma_clean["h2s_ge_10_event"] = h2s_rtma_clean["valid_h2s_record"] & (h2s_rtma_clean["h2s_ppb"] >= 10)
h2s_rtma_clean["orange_h2s_event"] = h2s_rtma_clean["valid_h2s_record"] & (h2s_rtma_clean["h2s_ppb"] >= 30)

# Add cleaned level labels based on H2S value
h2s_rtma_clean["h2s_level_clean"] = np.select(
    [
        h2s_rtma_clean["h2s_ppb"].isna(),
        h2s_rtma_clean["h2s_ppb"] < 5,
        (h2s_rtma_clean["h2s_ppb"] >= 5) & (h2s_rtma_clean["h2s_ppb"] < 30),
        h2s_rtma_clean["h2s_ppb"] >= 30
    ],
    [
        "Missing/Not visible",
        "Green (0-4.9 ppB)",
        "Yellow (5-29.9 ppB)",
        "Orange (30+ ppB)"
    ],
    default="Check"
)

# Add useful time fields
h2s_rtma_clean["year"] = h2s_rtma_clean["datetime_local"].dt.year
h2s_rtma_clean["month"] = h2s_rtma_clean["datetime_local"].dt.to_period("M").astype(str)
h2s_rtma_clean["hour"] = h2s_rtma_clean["datetime_local"].dt.hour

# Document the subset definition directly in the dataset
h2s_rtma_clean["rtma_match_subset_definition"] = "H2S events >= 10 ppb matched to hourly RTMA weather/wind variables"

# Organize most useful columns first
front_cols = [
    "datetime_local",
    "datetime_utc",
    "date",
    "year",
    "month",
    "hour",
    "location_clean",
    "target_lat",
    "target_lon",
    "h2s_ppb",
    "h2s_level_clean",
    "valid_h2s_record",
    "elevated_h2s_event",
    "h2s_ge_10_event",
    "orange_h2s_event",
    "temperature_2m_f",
    "dewpoint_2m_f",
    "wind_speed_10m_mph",
    "wind_direction_10m",
    "wind_gust_10m_mph",
    "visibility_surface_miles",
    "temperature_2m",
    "dewpoint_2m",
    "wind_u_10m",
    "wind_v_10m",
    "wind_speed_10m",
    "wind_gust_10m",
    "visibility_surface",
    "nighttime_flag",
    "analysis_period",
    "rtma_match_subset_definition"
]

# Keep remaining original columns after the organized front columns
remaining_cols = [col for col in h2s_rtma_clean.columns if col not in front_cols]
h2s_rtma_clean = h2s_rtma_clean[front_cols + remaining_cols].sort_values(
    ["datetime_local", "location_clean"]
).reset_index(drop=True)

print("Cleaned H2S + RTMA matched dataset created")
print("=" * 60)
print("Rows:", h2s_rtma_clean.shape[0])
print("Columns:", h2s_rtma_clean.shape[1])

print("\nDate/time coverage:")
print("Start datetime_local:", h2s_rtma_clean["datetime_local"].min())
print("End datetime_local:", h2s_rtma_clean["datetime_local"].max())
print("Unique dates:", h2s_rtma_clean["date"].nunique())
print("Unique stations:", h2s_rtma_clean["location_clean"].nunique())

print("\nEvent counts:")
print("Valid H2S records:", h2s_rtma_clean["valid_h2s_record"].sum())
print("H2S events >= 5 ppb:", h2s_rtma_clean["elevated_h2s_event"].sum())
print("H2S events >= 10 ppb:", h2s_rtma_clean["h2s_ge_10_event"].sum())
print("Orange H2S events >= 30 ppb:", h2s_rtma_clean["orange_h2s_event"].sum())

print("\nMissing values in key weather/wind columns:")
key_weather_cols = [
    "temperature_2m_f",
    "dewpoint_2m_f",
    "wind_speed_10m_mph",
    "wind_direction_10m",
    "wind_gust_10m_mph",
    "visibility_surface_miles"
]
print(h2s_rtma_clean[key_weather_cols].isna().sum())

print("\nPreview:")
display(h2s_rtma_clean.head())

Cleaned H2S + RTMA matched dataset created
============================================================
Rows: 60
Columns: 61

Date/time coverage:
Start datetime_local: 2024-09-25 19:00:00
End datetime_local: 2025-07-08 04:00:00
Unique dates: 11
Unique stations: 3

Event counts:
Valid H2S records: 60
H2S events >= 5 ppb: 60
H2S events >= 10 ppb: 60
Orange H2S events >= 30 ppb: 11

Missing values in key weather/wind columns:
temperature_2m_f            0
dewpoint_2m_f               0
wind_speed_10m_mph          0
wind_direction_10m          0
wind_gust_10m_mph           0
visibility_surface_miles    0
dtype: int64

Preview:

,datetime_local,datetime_utc,date,year,month,hour,location_clean,target_lat,target_lon,h2s_ppb,...,wind_gust_10m_grid_lon,visibility_surface_units,visibility_surface_grid_lat,visibility_surface_grid_lon,visibility_surface_km,time,datetime_utc_original,h2s_level,exceedance_30ppb,exceedance_200ppb
0,2024-09-25 19:00:00,2024-09-26 02:00:00,2024-09-25,2024,2024-09,19,SAN YSIDRO,32.552,-117.0431,10.0,...,-117.038140,m,32.550775,-117.038140,14.221,7:00:00 PM,2024-09-26 02:00:00+00:00,Yellow (5-29.9 ppB),0,0
1,2024-12-07 00:00:00,2024-12-07 08:00:00,2024-12-07,2024,2024-12,0,NESTOR - BES,32.579,-117.0910,17.8,...,-117.099856,m,32.588111,-117.099856,5.399,12:00:00 AM,2024-12-07 08:00:00+00:00,Yellow (5-29.9 ppB),0,0
2,2024-12-07 00:00:00,2024-12-07 08:00:00,2024-12-07,2024,2024-12,0,SAN YSIDRO,32.552,-117.0431,10.8,...,-117.038140,m,32.550775,-117.038140,12.146,12:00:00 AM,2024-12-07 08:00:00+00:00,Yellow (5-29.9 ppB),0,0
3,2024-12-07 01:00:00,2024-12-07 09:00:00,2024-12-07,2024,2024-12,1,NESTOR - BES,32.579,-117.0910,20.1,...,-117.099856,m,32.588111,-117.099856,11.989,1:00:00 AM,2024-12-07 09:00:00+00:00,Yellow (5-29.9 ppB),0,0
4,2024-12-07 01:00:00,2024-12-07 09:00:00,2024-12-07,2024,2024-12,1,SAN YSIDRO,32.552,-117.0431,15.0,...,-117.038140,m,32.550775,-117.038140,12.442,1:00:00 AM,2024-12-07 09:00:00+00:00,Yellow (5-29.9 ppB),0,0

In [ ]:
# now lets match the data point to stations and variables
print("H2S + RTMA cleaned QA summary")
print("=" * 60)

print("Overall dataset:")
print("Rows:", len(h2s_rtma_clean))
print("Unique dates:", h2s_rtma_clean["date"].nunique())
print("Unique stations:", h2s_rtma_clean["location_clean"].nunique())
print("Duplicate rows:", h2s_rtma_clean.duplicated().sum())

print("\nDuplicate checks using datetime + station:")
print(
    h2s_rtma_clean.duplicated(
        subset=["datetime_local", "location_clean"]
    ).sum()
)

print("\nStation-level summary:")
h2s_rtma_station_summary = (
    h2s_rtma_clean
    .groupby("location_clean", dropna=False)
    .agg(
        matched_events=("h2s_ppb", "size"),
        mean_h2s_ppb=("h2s_ppb", "mean"),
        median_h2s_ppb=("h2s_ppb", "median"),
        max_h2s_ppb=("h2s_ppb", "max"),
        orange_h2s_events=("orange_h2s_event", "sum"),
        mean_wind_speed_mph=("wind_speed_10m_mph", "mean"),
        median_wind_speed_mph=("wind_speed_10m_mph", "median"),
        max_wind_gust_mph=("wind_gust_10m_mph", "max"),
        mean_temperature_f=("temperature_2m_f", "mean"),
        mean_dewpoint_f=("dewpoint_2m_f", "mean"),
        mean_visibility_miles=("visibility_surface_miles", "mean")
    )
    .reset_index()
    .sort_values("matched_events", ascending=False)
)

display(h2s_rtma_station_summary)

print("\nWeather/wind variable summary:")
weather_summary_cols = [
    "h2s_ppb",
    "temperature_2m_f",
    "dewpoint_2m_f",
    "wind_speed_10m_mph",
    "wind_direction_10m",
    "wind_gust_10m_mph",
    "visibility_surface_miles"
]

display(h2s_rtma_clean[weather_summary_cols].describe())

print("\nH2S level counts:")
print(h2s_rtma_clean["h2s_level_clean"].value_counts(dropna=False))

print("\nEvents by month:")
display(
    h2s_rtma_clean
    .groupby("month")
    .agg(
        matched_events=("h2s_ppb", "size"),
        orange_h2s_events=("orange_h2s_event", "sum"),
        mean_h2s_ppb=("h2s_ppb", "mean"),
        max_h2s_ppb=("h2s_ppb", "max")
    )
    .reset_index()
)

H2S + RTMA cleaned QA summary
============================================================
Overall dataset:
Rows: 60
Unique dates: 11
Unique stations: 3
Duplicate rows: 0

Duplicate checks using datetime + station:
0

Station-level summary:

,location_clean,matched_events,mean_h2s_ppb,median_h2s_ppb,max_h2s_ppb,orange_h2s_events,mean_wind_speed_mph,median_wind_speed_mph,max_wind_gust_mph,mean_temperature_f,mean_dewpoint_f,mean_visibility_miles
1,NESTOR - BES,31,46.154839,16.70,295.6,7,3.022755,2.796175,9.932014,57.710970,52.231415,7.598066
2,SAN YSIDRO,20,21.525000,18.35,45.5,4,2.963945,2.203386,13.287424,59.923401,52.151898,7.996850
0,IB CIVIC CTR,9,16.222222,15.50,27.9,0,3.442402,3.668582,7.985876,57.715992,50.282008,7.013641

Weather/wind variable summary:

,h2s_ppb,temperature_2m_f,dewpoint_2m_f,wind_speed_10m_mph,wind_direction_10m,wind_gust_10m_mph,visibility_surface_miles
count,60.00000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,33.45500,58.449200,51.912498,3.066099,181.941668,4.834773,7.643330
std,53.36997,4.860501,10.176912,2.079414,111.226524,2.430415,2.599343
min,10.00000,44.311982,20.677974,0.000000,0.000000,0.715821,0.090720
25%,12.35000,55.179493,46.057985,1.554673,90.775002,3.114939,7.099805
50%,16.30000,59.297004,56.884984,2.617220,200.400002,4.596912,8.382318
75%,26.57500,61.349003,58.824482,4.496249,281.775002,6.280209,9.540402
max,295.60000,69.890022,61.286024,8.097723,358.700012,13.287424,9.941964

H2S level counts:
h2s_level_clean
Yellow (5-29.9 ppB)    49
Orange (30+ ppB)       11
Name: count, dtype: int64

Events by month:

     month  matched_events  orange_h2s_events  mean_h2s_ppb  max_h2s_ppb
0  2024-09               1                  0     10.000000         10.0
1  2024-12              20                  0     16.515000         29.8
2  2025-01               3                  0     12.066667         13.4
3  2025-05              34                 10     41.332353        295.6
4  2025-07               2                  1    112.750000        207.4

In [ ]:
# lets exports the cleaned H2S + RTMA matched event subset and station/month summaries
# for the final project

h2s_rtma_overall_summary = pd.DataFrame({
    "metric": [
        "total_matched_events",
        "unique_dates",
        "unique_stations",
        "start_datetime_local",
        "end_datetime_local",
        "mean_h2s_ppb",
        "median_h2s_ppb",
        "max_h2s_ppb",
        "h2s_events_ge_10ppb",
        "orange_h2s_events_ge_30ppb",
        "mean_wind_speed_mph",
        "median_wind_speed_mph",
        "max_wind_gust_mph",
        "mean_temperature_f",
        "mean_dewpoint_f",
        "mean_visibility_miles"
    ],
    "value": [
        len(h2s_rtma_clean),
        h2s_rtma_clean["date"].nunique(),
        h2s_rtma_clean["location_clean"].nunique(),
        str(h2s_rtma_clean["datetime_local"].min()),
        str(h2s_rtma_clean["datetime_local"].max()),
        round(h2s_rtma_clean["h2s_ppb"].mean(), 3),
        round(h2s_rtma_clean["h2s_ppb"].median(), 3),
        round(h2s_rtma_clean["h2s_ppb"].max(), 3),
        int(h2s_rtma_clean["h2s_ge_10_event"].sum()),
        int(h2s_rtma_clean["orange_h2s_event"].sum()),
        round(h2s_rtma_clean["wind_speed_10m_mph"].mean(), 3),
        round(h2s_rtma_clean["wind_speed_10m_mph"].median(), 3),
        round(h2s_rtma_clean["wind_gust_10m_mph"].max(), 3),
        round(h2s_rtma_clean["temperature_2m_f"].mean(), 3),
        round(h2s_rtma_clean["dewpoint_2m_f"].mean(), 3),
        round(h2s_rtma_clean["visibility_surface_miles"].mean(), 3)
    ]
})

h2s_rtma_station_summary = (
    h2s_rtma_clean
    .groupby("location_clean", dropna=False)
    .agg(
        matched_events=("h2s_ppb", "size"),
        unique_dates=("date", "nunique"),
        mean_h2s_ppb=("h2s_ppb", "mean"),
        median_h2s_ppb=("h2s_ppb", "median"),
        max_h2s_ppb=("h2s_ppb", "max"),
        orange_h2s_events=("orange_h2s_event", "sum"),
        mean_wind_speed_mph=("wind_speed_10m_mph", "mean"),
        median_wind_speed_mph=("wind_speed_10m_mph", "median"),
        max_wind_gust_mph=("wind_gust_10m_mph", "max"),
        mean_temperature_f=("temperature_2m_f", "mean"),
        mean_dewpoint_f=("dewpoint_2m_f", "mean"),
        mean_visibility_miles=("visibility_surface_miles", "mean")
    )
    .reset_index()
    .sort_values("matched_events", ascending=False)
)

h2s_rtma_month_summary = (
    h2s_rtma_clean
    .groupby("month", dropna=False)
    .agg(
        matched_events=("h2s_ppb", "size"),
        unique_stations=("location_clean", "nunique"),
        mean_h2s_ppb=("h2s_ppb", "mean"),
        median_h2s_ppb=("h2s_ppb", "median"),
        max_h2s_ppb=("h2s_ppb", "max"),
        orange_h2s_events=("orange_h2s_event", "sum"),
        mean_wind_speed_mph=("wind_speed_10m_mph", "mean"),
        max_wind_gust_mph=("wind_gust_10m_mph", "max")
    )
    .reset_index()
)

# Output paths
h2s_rtma_overall_summary_path = TABLES / "h2s_rtma_overall_summary.csv"
h2s_rtma_station_summary_path = TABLES / "h2s_rtma_station_summary.csv"
h2s_rtma_month_summary_path = TABLES / "h2s_rtma_month_summary.csv"

# Save files
h2s_rtma_clean.to_csv(rtma_matched_output_path, index=False)
h2s_rtma_overall_summary.to_csv(h2s_rtma_overall_summary_path, index=False)
h2s_rtma_station_summary.to_csv(h2s_rtma_station_summary_path, index=False)
h2s_rtma_month_summary.to_csv(h2s_rtma_month_summary_path, index=False)

# Reload cleaned file for QA
h2s_rtma_reloaded = pd.read_csv(rtma_matched_output_path)

print("Saved H2S + RTMA cleaned files")
print("=" * 60)

print("\nProcessed data file:")
print(rtma_matched_output_path)
print("File exists:", rtma_matched_output_path.exists())
print("Reloaded shape:", h2s_rtma_reloaded.shape)

print("\nSummary tables:")
for path in [
    h2s_rtma_overall_summary_path,
    h2s_rtma_station_summary_path,
    h2s_rtma_month_summary_path
]:
    print(path)
    print("File exists:", path.exists())

print("\nReloaded QA:")
print("Rows:", len(h2s_rtma_reloaded))
print("Unique dates:", h2s_rtma_reloaded["date"].nunique())
print("Unique stations:", h2s_rtma_reloaded["location_clean"].nunique())
print("H2S events >= 10 ppb:", h2s_rtma_reloaded["h2s_ge_10_event"].sum())
print("Orange H2S events >= 30 ppb:", h2s_rtma_reloaded["orange_h2s_event"].sum())

print("\nStation summary:")
display(h2s_rtma_station_summary)

Saved H2S + RTMA cleaned files
============================================================

Processed data file:
/content/drive/MyDrive/STAT596/Project596_datafiles/processed_data/h2s_rtma_matched_events_clean.csv
File exists: True
Reloaded shape: (60, 61)

Summary tables:
/content/drive/MyDrive/STAT596/Project596_datafiles/tables/h2s_rtma_overall_summary.csv
File exists: True
/content/drive/MyDrive/STAT596/Project596_datafiles/tables/h2s_rtma_station_summary.csv
File exists: True
/content/drive/MyDrive/STAT596/Project596_datafiles/tables/h2s_rtma_month_summary.csv
File exists: True

Reloaded QA:
Rows: 60
Unique dates: 11
Unique stations: 3
H2S events >= 10 ppb: 60
Orange H2S events >= 30 ppb: 11

Station summary:

,location_clean,matched_events,unique_dates,mean_h2s_ppb,median_h2s_ppb,max_h2s_ppb,orange_h2s_events,mean_wind_speed_mph,median_wind_speed_mph,max_wind_gust_mph,mean_temperature_f,mean_dewpoint_f,mean_visibility_miles
1,NESTOR - BES,31,9,46.154839,16.70,295.6,7,3.022755,2.796175,9.932014,57.710970,52.231415,7.598066
2,SAN YSIDRO,20,4,21.525000,18.35,45.5,4,2.963945,2.203386,13.287424,59.923401,52.151898,7.996850
0,IB CIVIC CTR,9,3,16.222222,15.50,27.9,0,3.442402,3.668582,7.985876,57.715992,50.282008,7.013641